name: grype
base: core24
version: "v0.79.4"
summary: Vulnerability scanner
description: |
  CLI vulnerability scanner for container images and filesystems

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  s390x:
    build-for: [s390x]
    build-on: [s390x]
  ppc64el:
    build-for: [ppc64el]
    build-on: [ppc64el]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]

grade: stable
confinement: classic

parts:
  grype:
    plugin: go
    source: https://github.com/anchore/$SNAPCRAFT_PROJECT_NAME/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    prime:
      - bin/grype
    build-snaps:
      - go

apps:
  grype:
    command: bin/grype

