name: grype
base: core24
version: "v0.100.0"
summary: Vulnerability scanner
description: |
  CLI vulnerability scanner for container images and filesystems

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
#  armhf:
#    build-on: [armhf]
#    build-for: [armhf]
  s390x:
    build-for: [s390x]
    build-on: [s390x]
  ppc64el:
    build-for: [ppc64el]
    build-on: [ppc64el]
#  riscv64:
#    build-on: [riscv64]
#    build-for: [riscv64]

grade: stable
confinement: classic

parts:
  grype:
    plugin: nil
    source: https://github.com/anchore/${SNAPCRAFT_PROJECT_NAME}/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/${SNAPCRAFT_PROJECT_NAME}_${SNAPCRAFT_PROJECT_VERSION}_linux_${CRAFT_ARCH_BUILD_FOR}.tar.gz
    override-pull: |
      upstream_arch="$CRAFT_ARCH_BUILD_FOR"
      # Go releaser uses a different nomenclature for architecture on ppc64
      if [ "$CRAFT_ARCH_BUILD_FOR" == "ppc64el" ]; then
        upstream_arch="ppc64le"
      fi
      ver_no_v=$(echo $SNAPCRAFT_PROJECT_VERSION | tr -d "v")
      wget -O grype.tar.gz https://github.com/anchore/${SNAPCRAFT_PROJECT_NAME}/releases/download/${SNAPCRAFT_PROJECT_VERSION}/${SNAPCRAFT_PROJECT_NAME}_${ver_no_v}_linux_${upstream_arch}.tar.gz
      tar zxvf grype.tar.gz
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin
      install LICENSE  "$SNAPCRAFT_PART_INSTALL"
      install README.md "$SNAPCRAFT_PART_INSTALL"
      install CHANGELOG.md "$SNAPCRAFT_PART_INSTALL"
      install grype "$SNAPCRAFT_PART_INSTALL"/bin
    build-packages:
      - wget

apps:
  grype:
    command: bin/grype

